server {
    listen       80;
    server_name  localhost;

    # 静态文件目录
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # 支持 Vue Router的 history 模式
        try_files $uri $uri/ /index.html;
    }

    # 若依前台请求后台的反向代理配置，生产环境接口带有 /prod-api 前缀
    location /prod-api/ {
        # proxy_pass 加上末尾斜杠，会将匹配到的 /prod-api/ 截断不发给后台
        proxy_pass http://spring-api:8080/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
